name: Run tests

on:
  repository_dispatch:
    types: run

env:
  IMAGE: "docker.pkg.github.com/${{ github.repository }}/dp-saksbehandling-funksjonelle-tester:${{ github.sha }}"
jobs:
  run:
    name: Run tests as a Job
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_USERNAME: dp-funksjonelle-tester
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/tests.yml
          PRINT_PAYLOAD: true
        timeout-minutes: 5
      - name: Notify of failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_TITLE:  'Test run failed'
          SLACK_MESSAGE: 'De funksjonelle testene feilet :sadcat:'
      - name: Notify of success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_TITLE:  'Test run passed'
          SLACK_MESSAGE: 'De funksjonelle testene passerte :medal:'