name: Cron job

on:
  schedule:
    # Run once every day
    - cron: '0 1 * * *'

env:
  IMAGE: "docker.pkg.github.com/${{ github.repository }}/dp-saksbehandling-funksjonelle-tester:${{ github.sha }}"
jobs:
  run:
    name: Run tests as a Job
    runs-on: ubuntu-latest
    if: ${{ 1 == 2 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/tests.yml
          VAR: app=scheduled-funksjonelle-tester
          PRINT_PAYLOAD: true
        timeout-minutes: 8
      - name: Notify of failure
        if: ${{ 1 == 2 }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_TITLE:  'Test run failed'
          SLACK_MESSAGE: 'De funksjonelle testene feilet :sadcat:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: dp-funksjonelle-tester
          SLACK_ICON_EMOJI: ':male-scientist:'
          MSG_MINIMAL: true